### ISSUE TITLE
Oauth2 token for this gem 

### ISSUE THREAD

**Issue by yatish27** [jorgevaldivia/salesforce_bulk#6]
If i am using Oauth2 for authentication.i can access the access token . so how shud i use that to use this gem rather tan the username and password

**Comment by jorgevaldivia** [comment]
Currently there is no support for Oauth2, only username + password. I do hope to add that functionality in subsequent releases though.

**Comment by yatish27** [comment]
hey i have tried to combine the databasedotcom gem which uses all authentication methods and this gem . will be uploading soon
